# Generated by Django 2.2.5 on 2019-10-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=4)),
                ('leader', models.CharField(max_length=100)),
                ('hex_colour', models.CharField(max_length=7)),
                ('leader_seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Constituency')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='incumbent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Party'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Region'),
        ),
    ]
