# Generated by Django 2.2.5 on 2019-10-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191027_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='leader_seat',
        ),
    ]
