# Generated by Django 2.2.5 on 2019-10-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_party_leader_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='leader_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Constituency'),
        ),
    ]
