# Generated by Django 2.1.2 on 2019-10-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191029_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='incumbent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Party'),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Region'),
        ),
    ]
