# Generated by Django 2.1.2 on 2019-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20191029_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
