# Generated by Django 2.1.2 on 2019-10-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20191029_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='id',
        ),
        migrations.AlterField(
            model_name='constituency',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
