# Generated by Django 2.1.2 on 2019-10-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20191030_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='leader_seat',
        ),
    ]
