# Generated by Django 2.1.2 on 2019-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_party_leader_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='raw_name',
            field=models.CharField(default='default', editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
