# Generated by Django 2.1.2 on 2019-10-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_constituency_raw_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='raw_name',
            field=models.CharField(max_length=300),
        ),
    ]
