# Generated by Django 2.1.2 on 2019-10-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20191030_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='raw_name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
