# Generated by Django 2.1.2 on 2019-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20191030_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
