# Generated by Django 2.1.2 on 2019-10-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20191030_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='raw_name',
            field=models.CharField(default='default', editable=False, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constituency',
            name='raw_name',
            field=models.CharField(editable=False, max_length=300, primary_key=True, serialize=False),
        ),
    ]
