# Generated by Django 2.1.2 on 2019-10-30 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20191030_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='seats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Constituency'),
        ),
    ]
