# Generated by Django 2.1.2 on 2019-10-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_party_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='raw_name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
