# Generated by Django 2.1.2 on 2019-10-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20191030_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
