# Generated by Django 2.1.2 on 2019-10-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20191031_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='party',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
