# Generated by Django 2.1.2 on 2019-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20191031_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='wider_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
