# Generated by Django 2.1.2 on 2019-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_region_wider_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
