# Generated by Django 2.1.2 on 2019-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20191031_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sample_size', models.IntegerField()),
                ('pollster', models.CharField(max_length=100)),
            ],
        ),
    ]
