# Generated by Django 3.0.3 on 2020-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_prediction_vote_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='vote_shares',
        ),
        migrations.AddField(
            model_name='prediction',
            name='vote_shares',
            field=models.ManyToManyField(null=True, to='main_app.Party'),
        ),
    ]
