# Generated by Django 3.0.3 on 2020-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20200827_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='vote_shares',
            field=models.ManyToManyField(null=True, related_name='_prediction_vote_shares_+', to='main_app.Prediction'),
        ),
    ]
