# Generated by Django 3.0.3 on 2020-08-27 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_auto_20200827_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='vote_shares',
        ),
        migrations.CreateModel(
            name='PartyPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_share', models.DecimalField(decimal_places=1, max_digits=4)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Party')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Prediction')),
            ],
        ),
    ]
