# Generated by Django 3.0.3 on 2020-08-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20200827_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyprediction',
            name='prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Prediction'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
